# Generated by Django 2.0.2 on 2018-06-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='ans',
            field=models.TextField(default=''),
        ),
    ]
